name: 'Update'
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '07 03 * * 1'
defaults:
  run:
    shell: bash
jobs:
  Update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Set environmental variables"
        run: |
          echo "CTAC_LIBRARY_ID=4xR0aydMQb6s33qVGMELeg" >> $GITHUB_ENV
      - name: Install tools
        run: |
          sudo apt -y update
          sudo apt install -y libxml-simple-perl libwww-curl-perl libjson-pp-perl
      - name: Generate web page
        run: |
          ./publications.pl ${{ secrets.NASA_ADS_API_TOKEN }} ${CTAC_LIBRARY_ID} ./CTACers.xml
      - name: Push updates
        run: |
          git checkout gh-pages
          git config --local user.email "github@users.noreply.github.com"
          git config --local user.name "github-action-validate"
          git add publications.html
          git commit -m "Update publications"
          git push --set-upstream origin gh-pages
          git checkout -
